# file --mime-type -b sudolightburn.sh
# to see mimetype

# xdg-mime query default text/plain
# to see current

# xdg-mime default codium.desktop text/plain
# to change

# .desktop files should be in /usr/share/applications
# https://askubuntu.com/questions/16580/where-are-file-associations-stored

# cat /usr/share/applications/defaults.list
# to see defaults (system ones?)
# can be located with following command:
# locate defaults.list

# cat ~/.config/mimeapps.list
# to user specifc stuff, at least in Lubuntu 20.04


---
# is this task actually needed?
# var definition:
# xdg_mime_config_dir: "{{ lookup('env','HOME') }}/.config"
#
#- name: ensure users xdg mime directory exists
#  file:
#    state: directory
#    path: "{{ xdg_mime_config_dir }}"
#    mode: 0700
- name: Install packages with xdg-mime and other helper tools
  apt:
   name:
     - xdg-utils
     - mlocate
   force_apt_get: yes

- name: Set plain text files to be opened with Codium
  command: "xdg-mime default codium.desktop text/plain"
  changed_when: False

- name: Set files with shell scripts to be opened with Codium
  command: "xdg-mime default codium.desktop application/x-shellscript"
  changed_when: False

- name: Set pdf files to be opened with Okular
  command: "xdg-mime default okularApplication_pdf.desktop application/pdf"
  changed_when: False

# ???? is it correct? test
# xdg-mime query default application/epub+zip
- name: Set epubs files to be opened with Okular
  command: "xdg-mime default okularApplication_epup.desktop application/epub+zip"
  changed_when: False
