---
# is this task actually needed?
# var definition:
# xdg_mime_config_dir: "{{ lookup('env','HOME') }}/.config"
#
#- name: ensure users xdg mime directory exists
#  file:
#    state: directory
#    path: "{{ xdg_mime_config_dir }}"
#    mode: 0700
- name: Install package with xdg-mime
  apt:
   name:
     - xdg-utils
   force_apt_get: yes

- name: Set plain text files to be opened with Codium
  command: "xdg-mime default codium.desktop text/plain"
  changed_when: False

- name: Set files with shell scripts to be opened with Codium
  command: "xdg-mime default codium.desktop application/x-shellscript"
  changed_when: False

- name: Set pdf files to be opened with Okular
  command: "xdg-mime default okularApplication_pdf.desktop application/pdf"
  changed_when: False

# ???? is it correct? test
# xdg-mime query default application/epub+zip
- name: Set epubs files to be opened with Okular
  command: "xdg-mime default okularApplication_epup.desktop application/epub+zip"
  changed_when: False
