# https://docs.ansible.com/ansible/latest/modules/pip_module.html
---
- name: Install youtube-dl
  become: yes
  become_user: mateusz
  pip:
    name: youtube-dl
    extra_args: --user
    state: latest
