---
- name: core
  hosts: all
  become: yes
  roles:
    - ansible

- name: basic
  hosts: all
  become: yes
  roles:
    - git
    - ruby # required by legacy install scripts
    - python # required by commitment device scripts
    - basic_dev_tools
    - backup_restore_gem

- name: all_my_software
  hosts: all
  become: yes
  roles:
    - keepass
    - bloat_removal
