---
- name: core
  hosts: all
  become: yes
  roles:
    - ansible

- name: basic
  hosts: all
  become: yes
  roles:
    - git
    - ruby
    - basic_dev_tools

- name: all_my_software
  hosts: all
  become: yes
  roles:
    - keepass
