---
- name: Run apt-smart to select fastest mirror, as official mirror in Poland is slow and buggy
  command: /usr/local/bin//apt-smart -a
  args:
    creates: /tmp/apt-smart-was-run-recently
- name: Create file to mark that apt-smart was just completed
  file: 
    path: /tmp/apt-smart-was-run-recently 
    state: touch
#  command: touch /tmp/apt-smart-was-run-recently
#  args:
#    creates: /tmp/apt-smart-was-run-recently
