# https://docs.ansible.com/ansible/latest/modules/gem_module.html
---
- name: Install backup_restore gem for user
  become: yes
  become_user: "{{ username_of_a_local_user }}"
  gem:
   name: backup_restore
- name: Install backup_restore gem for the entire system
  gem:
   name: backup_restore
   user_install: false
