# https://docs.ansible.com/ansible/latest/modules/gem_module.html
---
- name: Install backup_restore for user
  gem:
   name: backup_restore
- name: Install backup_restore for the entire system
  gem:
   name: backup_restore
   user_install: false
