# installing
# nodejs
# apt package without adding special repos was not working well
# and this code is not tested on a fresh system

# official version is at
# https://github.com/nodesource/ansible-nodejs-role/blob/master/tasks/main.yml

# use it if simplified one below from HSKRK breaks

- name: Add apt key for node
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add repository for node
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_13.x {{ ansible_distribution_release }} main"

- name: Install node
  apt:
    pkg:
      - nodejs
