# https://docs.ansible.com/ansible/latest/modules/pip_module.html
---
- name: Upgrade pip
  become: yes
  become_user: "{{ username_of_a_local_user }}"
  pip:
    name: pip
    extra_args: --user
    state: latest
- name: Upgrade root pip
  pip:
    name: pip
    state: latest
