---
- name: Install packages
  apt:
   name:
     - unzip
     - curl
     - build-essential
     - software-properties-common
     - bash-completion  #supports autocompletion on tab in bash
     - autoconf
     - valgrind
   force_apt_get: yes
